{
 "title": "Istio Canary",
 "tags": [
  "flagger",
  "istio",
  "canary"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace" },
   { "name": "primary", "label": "Primary" },
   { "name": "canary", "label": "Canary" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"dashboard-header text-center\"><span>RED: $canary.$namespace</span></div>"
  },
  {
   "title": "Primary: Incoming Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$primary\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Incoming Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "avg" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$primary\",response_code!~\"5.*\"}[2m])) / sum(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$primary\"}[2m]))"
    }
   ]
  },
  {
   "title": "Canary: Incoming Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$canary\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Incoming Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$canary\",response_code!~\"5.*\"}[2m])) / sum(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$canary\"}[2m]))"
    }
   ]
  },
  {
   "title": "Primary: Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$primary\", destination_workload_namespace=~\"$namespace\"}[2m])) by (le)) / 1000",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$primary\", destination_workload_namespace=~\"$namespace\"}[2m])) by (le)) / 1000",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$primary\", destination_workload_namespace=~\"$namespace\"}[2m])) by (le)) / 1000",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Canary: Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$canary\", destination_workload_namespace=~\"$namespace\"}[2m])) by (le)) / 1000",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$canary\", destination_workload_namespace=~\"$namespace\"}[2m])) by (le)) / 1000",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$canary\", destination_workload_namespace=~\"$namespace\"}[2m])) by (le)) / 1000",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}