{
 "title": "Kubernetes App Metrics",
 "tags": [
  "kubernetes",
  "app-metrics"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace" },
   { "name": "container", "label": "Container" }
  ]
 },
 "panels": [
  {
   "title": "Number of pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (node))",
     "legendFormat": "hosts"
    }
   ]
  },
  {
   "title": "CPU usage (relative to request)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\"}[5m])) by (namespace,container) / sum(container_spec_cpu_shares{container=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container)",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "CPU usage (per pod)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) / count(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory usage (per pod)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) / count(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (container,namespace)",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}